[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
fs_permissions = [{ access = "read-write", path = ".forge-snapshots/"},{ access = "read", path = "./out" },{ access = "read-write", path = "./" }]
solc_version = "0.8.26"
evm_version = "cancun"
remappings = [
    "@uniswap/v4-core/=lib/v4-core/",
    "forge-gas-snapshot/=lib/v4-core/lib/forge-gas-snapshot/src/",
    "forge-std/=lib/v4-core/lib/forge-std/src/",
    "permit2/=lib/v4-periphery/lib/permit2/",
    "solmate/=lib/v4-core/lib/solmate/",
    "v4-core/=lib/v4-core/",
    "v4-periphery/=lib/v4-periphery/",
    "uniguard-avs/=lib/capstone-avs/",
    # OpenZeppelinのremappingを明示的に指定
    "@openzeppelin/contracts/=lib/capstone-avs/contracts/lib/eigenlayer-middleware/lib/eigenlayer-contracts/lib/openzeppelin-contracts/contracts/",
    "@openzeppelin-upgrades/=lib/capstone-avs/contracts/lib/eigenlayer-middleware/lib/eigenlayer-contracts/lib/openzeppelin-contracts-upgradeable/",
    "@eigenlayer/=lib/eigenlayer-contracts/src/",
    "@eigenlayer-middleware/=lib/capstone-avs/contracts/lib/eigenlayer-middleware/"
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config